# Generated by Django 2.0 on 2021-03-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_auto_20210317_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(default='male', max_length=50)),
                ('Service', models.CharField(default='service', max_length=50)),
                ('Phonnumber', models.IntegerField(default=123456789012, max_length=12)),
                ('Description', models.CharField(default='Description', max_length=50)),
                ('Status', models.CharField(default='Status', max_length=50)),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.Doctor')),
                ('patid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.Patient')),
            ],
        ),
    ]
