# Generated by Django 2.0 on 2021-03-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='docid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patid',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
