# Generated by Django 2.0 on 2021-03-25 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0005_auto_20210325_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='Enter Email', max_length=25, unique=True)),
                ('Password', models.CharField(default='', max_length=25)),
                ('Role', models.CharField(default='', max_length=25)),
                ('Otp', models.IntegerField(default=123456, max_length=6)),
                ('Is_created', models.DateTimeField(auto_now_add=True)),
                ('Is_verified', models.BooleanField(default=False)),
                ('Is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(default='male', max_length=50)),
                ('Service', models.CharField(default='service', max_length=50)),
                ('Phonnumber', models.IntegerField(default=123456789012, max_length=12)),
                ('Description', models.CharField(default='Description', max_length=50)),
                ('Status', models.CharField(default='Status', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='firstname', max_length=100)),
                ('Lastname', models.CharField(default='lastname', max_length=100)),
                ('Address', models.CharField(default='address', max_length=100)),
                ('Age', models.BigIntegerField(default=10, max_length=100)),
                ('Phonenumber', models.IntegerField(default=5454554, max_length=15)),
                ('Department', models.CharField(default='department', max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='firstname', max_length=100)),
                ('Lastname', models.CharField(default='lastname', max_length=100)),
                ('Address', models.CharField(default='address', max_length=100)),
                ('Age', models.IntegerField(default=10, max_length=12)),
                ('Phonenumber', models.IntegerField(default=123456789012, max_length=12)),
                ('Gender', models.CharField(default='male', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.Admin')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='docid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.Patient'),
        ),
    ]
